import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const STOCKS = [
  // ===== TECH (Major) =====
  { symbol: "AAPL", name: "Apple Inc", sector: "Tech" },
  { symbol: "MSFT", name: "Microsoft Corp", sector: "Tech" },
  { symbol: "GOOGL", name: "Alphabet Inc Class A", sector: "Tech" },
  { symbol: "GOOG", name: "Alphabet Inc Class C", sector: "Tech" },
  { symbol: "AMZN", name: "Amazon.com Inc", sector: "Tech" },
  { symbol: "META", name: "Meta Platforms Inc", sector: "Tech" },
  { symbol: "NVDA", name: "NVIDIA Corp", sector: "Tech" },
  { symbol: "TSM", name: "Taiwan Semiconductor", sector: "Tech" },
  { symbol: "AVGO", name: "Broadcom Inc", sector: "Tech" },
  { symbol: "ORCL", name: "Oracle Corp", sector: "Tech" },
  { symbol: "CRM", name: "Salesforce Inc", sector: "Tech" },
  { symbol: "ADBE", name: "Adobe Inc", sector: "Tech" },
  { symbol: "ACN", name: "Accenture PLC", sector: "Tech" },
  { symbol: "CSCO", name: "Cisco Systems Inc", sector: "Tech" },
  { symbol: "IBM", name: "International Business Machines", sector: "Tech" },
  { symbol: "INTC", name: "Intel Corp", sector: "Tech" },
  { symbol: "AMD", name: "Advanced Micro Devices", sector: "Tech" },
  { symbol: "QCOM", name: "Qualcomm Inc", sector: "Tech" },
  { symbol: "TXN", name: "Texas Instruments", sector: "Tech" },
  { symbol: "INTU", name: "Intuit Inc", sector: "Tech" },
  { symbol: "AMAT", name: "Applied Materials Inc", sector: "Tech" },
  { symbol: "NOW", name: "ServiceNow Inc", sector: "Tech" },
  { symbol: "SNPS", name: "Synopsys Inc", sector: "Tech" },
  { symbol: "CDNS", name: "Cadence Design Systems", sector: "Tech" },
  { symbol: "LRCX", name: "Lam Research Corp", sector: "Tech" },
  { symbol: "KLAC", name: "KLA Corp", sector: "Tech" },
  { symbol: "ADI", name: "Analog Devices Inc", sector: "Tech" },
  { symbol: "MU", name: "Micron Technology Inc", sector: "Tech" },
  { symbol: "PANW", name: "Palo Alto Networks", sector: "Tech" },
  { symbol: "MRVL", name: "Marvell Technology", sector: "Tech" },
  { symbol: "FTNT", name: "Fortinet Inc", sector: "Tech" },
  { symbol: "MSI", name: "Motorola Solutions Inc", sector: "Tech" },
  { symbol: "ADSK", name: "Autodesk Inc", sector: "Tech" },
  { symbol: "NXPI", name: "NXP Semiconductors", sector: "Tech" },
  { symbol: "CRWD", name: "CrowdStrike Holdings", sector: "Tech" },
  { symbol: "MCHP", name: "Microchip Technology", sector: "Tech" },
  { symbol: "ON", name: "ON Semiconductor Corp", sector: "Tech" },
  { symbol: "DELL", name: "Dell Technologies Inc", sector: "Tech" },
  { symbol: "HPQ", name: "HP Inc", sector: "Tech" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", sector: "Tech" },
  { symbol: "SMCI", name: "Super Micro Computer", sector: "Tech" },
  { symbol: "ARM", name: "Arm Holdings PLC", sector: "Tech" },
  { symbol: "SHOP", name: "Shopify Inc", sector: "Tech" },
  { symbol: "SQ", name: "Block Inc", sector: "Tech" },
  { symbol: "SNOW", name: "Snowflake Inc", sector: "Tech" },
  { symbol: "NET", name: "Cloudflare Inc", sector: "Tech" },
  { symbol: "DDOG", name: "Datadog Inc", sector: "Tech" },
  { symbol: "ZS", name: "Zscaler Inc", sector: "Tech" },
  { symbol: "WDAY", name: "Workday Inc", sector: "Tech" },
  { symbol: "TEAM", name: "Atlassian Corp", sector: "Tech" },
  { symbol: "HUBS", name: "HubSpot Inc", sector: "Tech" },
  { symbol: "DOCU", name: "DocuSign Inc", sector: "Tech" },
  { symbol: "MDB", name: "MongoDB Inc", sector: "Tech" },
  { symbol: "OKTA", name: "Okta Inc", sector: "Tech" },
  { symbol: "VEEV", name: "Veeva Systems Inc", sector: "Tech" },
  { symbol: "SPLK", name: "Splunk Inc", sector: "Tech" },
  { symbol: "TWLO", name: "Twilio Inc", sector: "Tech" },
  { symbol: "ZM", name: "Zoom Video Communications", sector: "Tech" },
  { symbol: "U", name: "Unity Software Inc", sector: "Tech" },
  { symbol: "PATH", name: "UiPath Inc", sector: "Tech" },
  { symbol: "ESTC", name: "Elastic NV", sector: "Tech" },
  { symbol: "CFLT", name: "Confluent Inc", sector: "Tech" },
  { symbol: "GTLB", name: "GitLab Inc", sector: "Tech" },
  { symbol: "IOT", name: "Samsara Inc", sector: "Tech" },
  { symbol: "GEN", name: "Gen Digital Inc", sector: "Tech" },
  { symbol: "CTSH", name: "Cognizant Technology Solutions", sector: "Tech" },
  { symbol: "IT", name: "Gartner Inc", sector: "Tech" },
  { symbol: "EPAM", name: "EPAM Systems Inc", sector: "Tech" },
  { symbol: "STX", name: "Seagate Technology", sector: "Tech" },
  { symbol: "WDC", name: "Western Digital Corp", sector: "Tech" },
  { symbol: "GDDY", name: "GoDaddy Inc", sector: "Tech" },
  { symbol: "AKAM", name: "Akamai Technologies", sector: "Tech" },
  { symbol: "ENPH", name: "Enphase Energy Inc", sector: "Tech" },
  { symbol: "MPWR", name: "Monolithic Power Systems", sector: "Tech" },
  { symbol: "SWKS", name: "Skyworks Solutions Inc", sector: "Tech" },
  { symbol: "QRVO", name: "Qorvo Inc", sector: "Tech" },
  { symbol: "TER", name: "Teradyne Inc", sector: "Tech" },
  { symbol: "KEYS", name: "Keysight Technologies", sector: "Tech" },
  { symbol: "ZBRA", name: "Zebra Technologies", sector: "Tech" },
  { symbol: "TRMB", name: "Trimble Inc", sector: "Tech" },
  { symbol: "PTC", name: "PTC Inc", sector: "Tech" },
  { symbol: "ANSS", name: "ANSYS Inc", sector: "Tech" },
  { symbol: "BSY", name: "Bentley Systems Inc", sector: "Tech" },
  { symbol: "GRAB", name: "Grab Holdings Ltd", sector: "Tech" },

  // ===== AI / Artificial Intelligence =====
  { symbol: "PLTR", name: "Palantir Technologies", sector: "AI" },
  { symbol: "AI", name: "C3.ai Inc", sector: "AI" },
  { symbol: "SOUN", name: "SoundHound AI Inc", sector: "AI" },
  { symbol: "BBAI", name: "BigBear.ai Holdings", sector: "AI" },
  { symbol: "UPST", name: "Upstart Holdings Inc", sector: "AI" },
  { symbol: "AMBA", name: "Ambarella Inc", sector: "AI" },
  { symbol: "PRCT", name: "PROCEPT BioRobotics", sector: "AI" },
  { symbol: "GFAI", name: "Guardforce AI Co", sector: "AI" },
  { symbol: "SERV", name: "Serve Robotics Inc", sector: "AI" },

  // ===== QUANTUM =====
  { symbol: "IONQ", name: "IonQ Inc", sector: "Quantum" },
  { symbol: "RGTI", name: "Rigetti Computing Inc", sector: "Quantum" },
  { symbol: "QBTS", name: "D-Wave Quantum Inc", sector: "Quantum" },
  { symbol: "QUBT", name: "Quantum Computing Inc", sector: "Quantum" },

  // ===== HEALTHCARE =====
  { symbol: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { symbol: "LLY", name: "Eli Lilly and Co", sector: "Healthcare" },
  { symbol: "ABBV", name: "AbbVie Inc", sector: "Healthcare" },
  { symbol: "MRK", name: "Merck & Co Inc", sector: "Healthcare" },
  { symbol: "PFE", name: "Pfizer Inc", sector: "Healthcare" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
  { symbol: "DHR", name: "Danaher Corp", sector: "Healthcare" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare" },
  { symbol: "AMGN", name: "Amgen Inc", sector: "Healthcare" },
  { symbol: "GILD", name: "Gilead Sciences Inc", sector: "Healthcare" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc", sector: "Healthcare" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare" },
  { symbol: "MDT", name: "Medtronic PLC", sector: "Healthcare" },
  { symbol: "SYK", name: "Stryker Corp", sector: "Healthcare" },
  { symbol: "BSX", name: "Boston Scientific Corp", sector: "Healthcare" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare" },
  { symbol: "ZTS", name: "Zoetis Inc", sector: "Healthcare" },
  { symbol: "EW", name: "Edwards Lifesciences", sector: "Healthcare" },
  { symbol: "BDX", name: "Becton Dickinson & Co", sector: "Healthcare" },
  { symbol: "HCA", name: "HCA Healthcare Inc", sector: "Healthcare" },
  { symbol: "CI", name: "Cigna Group", sector: "Healthcare" },
  { symbol: "ELV", name: "Elevance Health Inc", sector: "Healthcare" },
  { symbol: "MCK", name: "McKesson Corp", sector: "Healthcare" },
  { symbol: "CVS", name: "CVS Health Corp", sector: "Healthcare" },
  { symbol: "MRNA", name: "Moderna Inc", sector: "Healthcare" },
  { symbol: "BIIB", name: "Biogen Inc", sector: "Healthcare" },
  { symbol: "GEHC", name: "GE HealthCare Technologies", sector: "Healthcare" },
  { symbol: "A", name: "Agilent Technologies", sector: "Healthcare" },
  { symbol: "IQV", name: "IQVIA Holdings Inc", sector: "Healthcare" },
  { symbol: "IDXX", name: "IDEXX Laboratories", sector: "Healthcare" },
  { symbol: "DXCM", name: "DexCom Inc", sector: "Healthcare" },
  { symbol: "ILMN", name: "Illumina Inc", sector: "Healthcare" },
  { symbol: "ALGN", name: "Align Technology Inc", sector: "Healthcare" },
  { symbol: "HOLX", name: "Hologic Inc", sector: "Healthcare" },
  { symbol: "WAT", name: "Waters Corp", sector: "Healthcare" },
  { symbol: "MTD", name: "Mettler-Toledo International", sector: "Healthcare" },
  { symbol: "PODD", name: "Insulet Corp", sector: "Healthcare" },
  { symbol: "INCY", name: "Incyte Corp", sector: "Healthcare" },
  { symbol: "EXAS", name: "Exact Sciences Corp", sector: "Healthcare" },
  { symbol: "NBIX", name: "Neurocrine Biosciences", sector: "Healthcare" },
  { symbol: "HZNP", name: "Horizon Therapeutics", sector: "Healthcare" },
  { symbol: "SGEN", name: "Seagen Inc", sector: "Healthcare" },
  { symbol: "NTRA", name: "Natera Inc", sector: "Healthcare" },
  { symbol: "RARE", name: "Ultragenyx Pharmaceutical", sector: "Healthcare" },

  // ===== FINANCE =====
  { symbol: "JPM", name: "JPMorgan Chase & Co", sector: "Finance" },
  { symbol: "V", name: "Visa Inc", sector: "Finance" },
  { symbol: "MA", name: "Mastercard Inc", sector: "Finance" },
  { symbol: "BAC", name: "Bank of America Corp", sector: "Finance" },
  { symbol: "WFC", name: "Wells Fargo & Co", sector: "Finance" },
  { symbol: "GS", name: "Goldman Sachs Group", sector: "Finance" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Finance" },
  { symbol: "BLK", name: "BlackRock Inc", sector: "Finance" },
  { symbol: "C", name: "Citigroup Inc", sector: "Finance" },
  { symbol: "SCHW", name: "Charles Schwab Corp", sector: "Finance" },
  { symbol: "AXP", name: "American Express Co", sector: "Finance" },
  { symbol: "SPGI", name: "S&P Global Inc", sector: "Finance" },
  { symbol: "CB", name: "Chubb Ltd", sector: "Finance" },
  { symbol: "CME", name: "CME Group Inc", sector: "Finance" },
  { symbol: "ICE", name: "Intercontinental Exchange", sector: "Finance" },
  { symbol: "PGR", name: "Progressive Corp", sector: "Finance" },
  { symbol: "MMC", name: "Marsh & McLennan Cos", sector: "Finance" },
  { symbol: "AON", name: "Aon PLC", sector: "Finance" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Finance" },
  { symbol: "PNC", name: "PNC Financial Services", sector: "Finance" },
  { symbol: "TFC", name: "Truist Financial Corp", sector: "Finance" },
  { symbol: "AIG", name: "American International Group", sector: "Finance" },
  { symbol: "MET", name: "MetLife Inc", sector: "Finance" },
  { symbol: "PRU", name: "Prudential Financial Inc", sector: "Finance" },
  { symbol: "ALL", name: "Allstate Corp", sector: "Finance" },
  { symbol: "TRV", name: "Travelers Companies Inc", sector: "Finance" },
  { symbol: "AFL", name: "Aflac Inc", sector: "Finance" },
  { symbol: "BK", name: "Bank of New York Mellon", sector: "Finance" },
  { symbol: "STT", name: "State Street Corp", sector: "Finance" },
  { symbol: "FITB", name: "Fifth Third Bancorp", sector: "Finance" },
  { symbol: "COF", name: "Capital One Financial", sector: "Finance" },
  { symbol: "DFS", name: "Discover Financial Services", sector: "Finance" },
  { symbol: "PYPL", name: "PayPal Holdings Inc", sector: "Finance" },
  { symbol: "FIS", name: "Fidelity National Information", sector: "Finance" },
  { symbol: "FISV", name: "Fiserv Inc", sector: "Finance" },
  { symbol: "GPN", name: "Global Payments Inc", sector: "Finance" },
  { symbol: "HOOD", name: "Robinhood Markets Inc", sector: "Finance" },
  { symbol: "SOFI", name: "SoFi Technologies Inc", sector: "Finance" },
  { symbol: "NU", name: "Nu Holdings Ltd", sector: "Finance" },
  { symbol: "AFRM", name: "Affirm Holdings Inc", sector: "Finance" },

  // ===== CONSUMER =====
  { symbol: "PG", name: "Procter & Gamble Co", sector: "Consumer" },
  { symbol: "KO", name: "Coca-Cola Co", sector: "Consumer" },
  { symbol: "PEP", name: "PepsiCo Inc", sector: "Consumer" },
  { symbol: "COST", name: "Costco Wholesale Corp", sector: "Consumer" },
  { symbol: "PM", name: "Philip Morris International", sector: "Consumer" },
  { symbol: "MO", name: "Altria Group Inc", sector: "Consumer" },
  { symbol: "MDLZ", name: "Mondelez International", sector: "Consumer" },
  { symbol: "CL", name: "Colgate-Palmolive Co", sector: "Consumer" },
  { symbol: "EL", name: "Estee Lauder Cos", sector: "Consumer" },
  { symbol: "KMB", name: "Kimberly-Clark Corp", sector: "Consumer" },
  { symbol: "STZ", name: "Constellation Brands", sector: "Consumer" },
  { symbol: "MKC", name: "McCormick & Co Inc", sector: "Consumer" },
  { symbol: "GIS", name: "General Mills Inc", sector: "Consumer" },
  { symbol: "K", name: "Kellanova", sector: "Consumer" },
  { symbol: "HSY", name: "Hershey Co", sector: "Consumer" },
  { symbol: "SJM", name: "J.M. Smucker Co", sector: "Consumer" },
  { symbol: "CAG", name: "Conagra Brands Inc", sector: "Consumer" },
  { symbol: "CPB", name: "Campbell Soup Co", sector: "Consumer" },
  { symbol: "HRL", name: "Hormel Foods Corp", sector: "Consumer" },
  { symbol: "KHC", name: "Kraft Heinz Co", sector: "Consumer" },
  { symbol: "CLX", name: "Clorox Co", sector: "Consumer" },
  { symbol: "CHD", name: "Church & Dwight Co", sector: "Consumer" },
  { symbol: "NKE", name: "Nike Inc", sector: "Consumer" },
  { symbol: "LULU", name: "Lululemon Athletica", sector: "Consumer" },
  { symbol: "DECK", name: "Deckers Outdoor Corp", sector: "Consumer" },
  { symbol: "SBUX", name: "Starbucks Corp", sector: "Consumer" },
  { symbol: "MCD", name: "McDonald's Corp", sector: "Consumer" },
  { symbol: "YUM", name: "Yum! Brands Inc", sector: "Consumer" },
  { symbol: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer" },
  { symbol: "DPZ", name: "Domino's Pizza Inc", sector: "Consumer" },
  { symbol: "QSR", name: "Restaurant Brands International", sector: "Consumer" },
  { symbol: "DASH", name: "DoorDash Inc", sector: "Consumer" },
  { symbol: "ABNB", name: "Airbnb Inc", sector: "Consumer" },
  { symbol: "BKNG", name: "Booking Holdings Inc", sector: "Consumer" },
  { symbol: "EXPE", name: "Expedia Group Inc", sector: "Consumer" },
  { symbol: "MAR", name: "Marriott International", sector: "Consumer" },
  { symbol: "HLT", name: "Hilton Worldwide Holdings", sector: "Consumer" },
  { symbol: "RCL", name: "Royal Caribbean Cruises", sector: "Consumer" },
  { symbol: "CCL", name: "Carnival Corp", sector: "Consumer" },

  // ===== RETAIL =====
  { symbol: "WMT", name: "Walmart Inc", sector: "Retail" },
  { symbol: "HD", name: "Home Depot Inc", sector: "Retail" },
  { symbol: "LOW", name: "Lowe's Companies Inc", sector: "Retail" },
  { symbol: "TGT", name: "Target Corp", sector: "Retail" },
  { symbol: "TJX", name: "TJX Companies Inc", sector: "Retail" },
  { symbol: "ROST", name: "Ross Stores Inc", sector: "Retail" },
  { symbol: "DG", name: "Dollar General Corp", sector: "Retail" },
  { symbol: "DLTR", name: "Dollar Tree Inc", sector: "Retail" },
  { symbol: "BURL", name: "Burlington Stores Inc", sector: "Retail" },
  { symbol: "BBY", name: "Best Buy Co Inc", sector: "Retail" },
  { symbol: "AZO", name: "AutoZone Inc", sector: "Retail" },
  { symbol: "ORLY", name: "O'Reilly Automotive", sector: "Retail" },
  { symbol: "AAP", name: "Advance Auto Parts", sector: "Retail" },
  { symbol: "GME", name: "GameStop Corp", sector: "Retail" },
  { symbol: "ETSY", name: "Etsy Inc", sector: "Retail" },
  { symbol: "W", name: "Wayfair Inc", sector: "Retail" },
  { symbol: "FIVE", name: "Five Below Inc", sector: "Retail" },
  { symbol: "ULTA", name: "Ulta Beauty Inc", sector: "Retail" },
  { symbol: "CAVA", name: "CAVA Group Inc", sector: "Retail" },

  // ===== ENERGY =====
  { symbol: "XOM", name: "Exxon Mobil Corp", sector: "Energy" },
  { symbol: "CVX", name: "Chevron Corp", sector: "Energy" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy" },
  { symbol: "EOG", name: "EOG Resources Inc", sector: "Energy" },
  { symbol: "SLB", name: "Schlumberger Ltd", sector: "Energy" },
  { symbol: "MPC", name: "Marathon Petroleum Corp", sector: "Energy" },
  { symbol: "PSX", name: "Phillips 66", sector: "Energy" },
  { symbol: "VLO", name: "Valero Energy Corp", sector: "Energy" },
  { symbol: "PXD", name: "Pioneer Natural Resources", sector: "Energy" },
  { symbol: "OXY", name: "Occidental Petroleum", sector: "Energy" },
  { symbol: "DVN", name: "Devon Energy Corp", sector: "Energy" },
  { symbol: "HAL", name: "Halliburton Co", sector: "Energy" },
  { symbol: "BKR", name: "Baker Hughes Co", sector: "Energy" },
  { symbol: "FANG", name: "Diamondback Energy", sector: "Energy" },
  { symbol: "WMB", name: "Williams Companies Inc", sector: "Energy" },
  { symbol: "KMI", name: "Kinder Morgan Inc", sector: "Energy" },
  { symbol: "OKE", name: "ONEOK Inc", sector: "Energy" },
  { symbol: "TRGP", name: "Targa Resources Corp", sector: "Energy" },
  { symbol: "HES", name: "Hess Corp", sector: "Energy" },
  { symbol: "EQT", name: "EQT Corp", sector: "Energy" },
  { symbol: "APA", name: "APA Corp", sector: "Energy" },
  { symbol: "CTRA", name: "Coterra Energy Inc", sector: "Energy" },
  { symbol: "AR", name: "Antero Resources Corp", sector: "Energy" },

  // ===== INDUSTRIAL =====
  { symbol: "GE", name: "GE Aerospace", sector: "Industrial" },
  { symbol: "CAT", name: "Caterpillar Inc", sector: "Industrial" },
  { symbol: "HON", name: "Honeywell International", sector: "Industrial" },
  { symbol: "UNP", name: "Union Pacific Corp", sector: "Industrial" },
  { symbol: "UPS", name: "United Parcel Service", sector: "Industrial" },
  { symbol: "DE", name: "Deere & Co", sector: "Industrial" },
  { symbol: "MMM", name: "3M Co", sector: "Industrial" },
  { symbol: "FDX", name: "FedEx Corp", sector: "Industrial" },
  { symbol: "EMR", name: "Emerson Electric Co", sector: "Industrial" },
  { symbol: "ETN", name: "Eaton Corp PLC", sector: "Industrial" },
  { symbol: "ITW", name: "Illinois Tool Works", sector: "Industrial" },
  { symbol: "WM", name: "Waste Management Inc", sector: "Industrial" },
  { symbol: "RSG", name: "Republic Services Inc", sector: "Industrial" },
  { symbol: "NSC", name: "Norfolk Southern Corp", sector: "Industrial" },
  { symbol: "CSX", name: "CSX Corp", sector: "Industrial" },
  { symbol: "GD", name: "General Dynamics Corp", sector: "Industrial" },
  { symbol: "PH", name: "Parker-Hannifin Corp", sector: "Industrial" },
  { symbol: "CARR", name: "Carrier Global Corp", sector: "Industrial" },
  { symbol: "CMI", name: "Cummins Inc", sector: "Industrial" },
  { symbol: "ROK", name: "Rockwell Automation", sector: "Industrial" },
  { symbol: "FAST", name: "Fastenal Co", sector: "Industrial" },
  { symbol: "PCAR", name: "PACCAR Inc", sector: "Industrial" },
  { symbol: "OTIS", name: "Otis Worldwide Corp", sector: "Industrial" },
  { symbol: "AME", name: "AMETEK Inc", sector: "Industrial" },
  { symbol: "IR", name: "Ingersoll Rand Inc", sector: "Industrial" },
  { symbol: "VRSK", name: "Verisk Analytics Inc", sector: "Industrial" },
  { symbol: "WAB", name: "Westinghouse Air Brake", sector: "Industrial" },
  { symbol: "DOV", name: "Dover Corp", sector: "Industrial" },
  { symbol: "GWW", name: "W.W. Grainger Inc", sector: "Industrial" },
  { symbol: "XYL", name: "Xylem Inc", sector: "Industrial" },
  { symbol: "SWK", name: "Stanley Black & Decker", sector: "Industrial" },

  // ===== AEROSPACE & DEFENSE =====
  { symbol: "BA", name: "Boeing Co", sector: "Aerospace" },
  { symbol: "LMT", name: "Lockheed Martin Corp", sector: "Defense" },
  { symbol: "RTX", name: "RTX Corp", sector: "Defense" },
  { symbol: "NOC", name: "Northrop Grumman Corp", sector: "Defense" },
  { symbol: "LHX", name: "L3Harris Technologies", sector: "Defense" },
  { symbol: "TDG", name: "TransDigm Group Inc", sector: "Aerospace" },
  { symbol: "HWM", name: "Howmet Aerospace Inc", sector: "Aerospace" },
  { symbol: "HII", name: "Huntington Ingalls Industries", sector: "Defense" },
  { symbol: "LDOS", name: "Leidos Holdings Inc", sector: "Defense" },
  { symbol: "AXON", name: "Axon Enterprise Inc", sector: "Defense" },
  { symbol: "RKLB", name: "Rocket Lab USA Inc", sector: "Aerospace" },
  { symbol: "LUNR", name: "Intuitive Machines Inc", sector: "Aerospace" },
  { symbol: "RDW", name: "Redwire Corp", sector: "Aerospace" },
  { symbol: "SPCE", name: "Virgin Galactic Holdings", sector: "Aerospace" },

  // ===== COMMUNICATION / MEDIA =====
  { symbol: "DIS", name: "Walt Disney Co", sector: "Media" },
  { symbol: "NFLX", name: "Netflix Inc", sector: "Media" },
  { symbol: "CMCSA", name: "Comcast Corp", sector: "Comm" },
  { symbol: "T", name: "AT&T Inc", sector: "Comm" },
  { symbol: "VZ", name: "Verizon Communications", sector: "Comm" },
  { symbol: "TMUS", name: "T-Mobile US Inc", sector: "Comm" },
  { symbol: "CHTR", name: "Charter Communications", sector: "Comm" },
  { symbol: "SPOT", name: "Spotify Technology SA", sector: "Media" },
  { symbol: "ROKU", name: "Roku Inc", sector: "Media" },
  { symbol: "WBD", name: "Warner Bros Discovery", sector: "Media" },
  { symbol: "PARA", name: "Paramount Global", sector: "Media" },
  { symbol: "FOX", name: "Fox Corp Class B", sector: "Media" },
  { symbol: "FOXA", name: "Fox Corp Class A", sector: "Media" },
  { symbol: "LYV", name: "Live Nation Entertainment", sector: "Media" },
  { symbol: "AMC", name: "AMC Entertainment Holdings", sector: "Media" },
  { symbol: "SNAP", name: "Snap Inc", sector: "Media" },
  { symbol: "PINS", name: "Pinterest Inc", sector: "Media" },
  { symbol: "RDDT", name: "Reddit Inc", sector: "Media" },
  { symbol: "TTD", name: "Trade Desk Inc", sector: "Media" },
  { symbol: "RBLX", name: "Roblox Corp", sector: "Media" },
  { symbol: "EA", name: "Electronic Arts Inc", sector: "Media" },
  { symbol: "TTWO", name: "Take-Two Interactive", sector: "Media" },
  { symbol: "MTCH", name: "Match Group Inc", sector: "Media" },
  { symbol: "IMAX", name: "IMAX Corp", sector: "Media" },
  { symbol: "LSXMA", name: "Liberty SiriusXM Group", sector: "Media" },

  // ===== AUTO / EV =====
  { symbol: "TSLA", name: "Tesla Inc", sector: "Auto" },
  { symbol: "F", name: "Ford Motor Co", sector: "Auto" },
  { symbol: "GM", name: "General Motors Co", sector: "Auto" },
  { symbol: "TM", name: "Toyota Motor Corp", sector: "Auto" },
  { symbol: "RIVN", name: "Rivian Automotive Inc", sector: "Auto" },
  { symbol: "LCID", name: "Lucid Group Inc", sector: "Auto" },
  { symbol: "NIO", name: "NIO Inc", sector: "Auto" },
  { symbol: "XPEV", name: "XPeng Inc", sector: "Auto" },
  { symbol: "LI", name: "Li Auto Inc", sector: "Auto" },
  { symbol: "APTV", name: "Aptiv PLC", sector: "Auto" },
  { symbol: "BWA", name: "BorgWarner Inc", sector: "Auto" },
  { symbol: "LEA", name: "Lear Corp", sector: "Auto" },
  { symbol: "ALV", name: "Autoliv Inc", sector: "Auto" },
  { symbol: "RACE", name: "Ferrari NV", sector: "Auto" },
  { symbol: "STLA", name: "Stellantis NV", sector: "Auto" },
  { symbol: "UBER", name: "Uber Technologies Inc", sector: "Auto" },
  { symbol: "LYFT", name: "Lyft Inc", sector: "Auto" },
  { symbol: "CHPT", name: "ChargePoint Holdings", sector: "Auto" },
  { symbol: "BLNK", name: "Blink Charging Co", sector: "Auto" },
  { symbol: "GOEV", name: "Canoo Inc", sector: "Auto" },

  // ===== CRYPTO =====
  { symbol: "COIN", name: "Coinbase Global Inc", sector: "Crypto" },
  { symbol: "MSTR", name: "MicroStrategy Inc", sector: "Crypto" },
  { symbol: "MARA", name: "Marathon Digital Holdings", sector: "Crypto" },
  { symbol: "RIOT", name: "Riot Platforms Inc", sector: "Crypto" },
  { symbol: "CLSK", name: "CleanSpark Inc", sector: "Crypto" },
  { symbol: "HUT", name: "Hut 8 Corp", sector: "Crypto" },
  { symbol: "BITF", name: "Bitfarms Ltd", sector: "Crypto" },
  { symbol: "IREN", name: "Iris Energy Ltd", sector: "Crypto" },
  { symbol: "CIFR", name: "Cipher Mining Inc", sector: "Crypto" },
  { symbol: "BTBT", name: "Bit Digital Inc", sector: "Crypto" },
  { symbol: "WULF", name: "TeraWulf Inc", sector: "Crypto" },
  { symbol: "CORZ", name: "Core Scientific Inc", sector: "Crypto" },

  // ===== REIT (Real Estate) =====
  { symbol: "PLD", name: "Prologis Inc", sector: "REIT" },
  { symbol: "AMT", name: "American Tower Corp", sector: "REIT" },
  { symbol: "CCI", name: "Crown Castle Inc", sector: "REIT" },
  { symbol: "EQIX", name: "Equinix Inc", sector: "REIT" },
  { symbol: "PSA", name: "Public Storage", sector: "REIT" },
  { symbol: "SPG", name: "Simon Property Group", sector: "REIT" },
  { symbol: "O", name: "Realty Income Corp", sector: "REIT" },
  { symbol: "WELL", name: "Welltower Inc", sector: "REIT" },
  { symbol: "DLR", name: "Digital Realty Trust", sector: "REIT" },
  { symbol: "VICI", name: "VICI Properties Inc", sector: "REIT" },
  { symbol: "AVB", name: "AvalonBay Communities", sector: "REIT" },
  { symbol: "EQR", name: "Equity Residential", sector: "REIT" },
  { symbol: "ARE", name: "Alexandria Real Estate", sector: "REIT" },
  { symbol: "MAA", name: "Mid-America Apartment", sector: "REIT" },
  { symbol: "UDR", name: "UDR Inc", sector: "REIT" },
  { symbol: "ESS", name: "Essex Property Trust", sector: "REIT" },
  { symbol: "IRM", name: "Iron Mountain Inc", sector: "REIT" },
  { symbol: "SBAC", name: "SBA Communications Corp", sector: "REIT" },
  { symbol: "WPC", name: "W.P. Carey Inc", sector: "REIT" },
  { symbol: "KIM", name: "Kimco Realty Corp", sector: "REIT" },

  // ===== MATERIALS =====
  { symbol: "LIN", name: "Linde PLC", sector: "Materials" },
  { symbol: "APD", name: "Air Products & Chemicals", sector: "Materials" },
  { symbol: "SHW", name: "Sherwin-Williams Co", sector: "Materials" },
  { symbol: "ECL", name: "Ecolab Inc", sector: "Materials" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc", sector: "Materials" },
  { symbol: "NEM", name: "Newmont Corp", sector: "Materials" },
  { symbol: "NUE", name: "Nucor Corp", sector: "Materials" },
  { symbol: "DOW", name: "Dow Inc", sector: "Materials" },
  { symbol: "DD", name: "DuPont de Nemours Inc", sector: "Materials" },
  { symbol: "PPG", name: "PPG Industries Inc", sector: "Materials" },
  { symbol: "VMC", name: "Vulcan Materials Co", sector: "Materials" },
  { symbol: "MLM", name: "Martin Marietta Materials", sector: "Materials" },
  { symbol: "CTVA", name: "Corteva Inc", sector: "Materials" },
  { symbol: "EMN", name: "Eastman Chemical Co", sector: "Materials" },
  { symbol: "ALB", name: "Albemarle Corp", sector: "Materials" },
  { symbol: "IFF", name: "International Flavors & Fragrances", sector: "Materials" },
  { symbol: "CE", name: "Celanese Corp", sector: "Materials" },
  { symbol: "CF", name: "CF Industries Holdings", sector: "Materials" },
  { symbol: "MOS", name: "Mosaic Co", sector: "Materials" },
  { symbol: "STLD", name: "Steel Dynamics Inc", sector: "Materials" },
  { symbol: "RS", name: "Reliance Steel & Aluminum", sector: "Materials" },
  { symbol: "GOLD", name: "Barrick Gold Corp", sector: "Materials" },
  { symbol: "AA", name: "Alcoa Corp", sector: "Materials" },
  { symbol: "X", name: "United States Steel Corp", sector: "Materials" },
  { symbol: "CLF", name: "Cleveland-Cliffs Inc", sector: "Materials" },
  { symbol: "MP", name: "MP Materials Corp", sector: "Materials" },

  // ===== UTILITIES =====
  { symbol: "NEE", name: "NextEra Energy Inc", sector: "Utilities" },
  { symbol: "SO", name: "Southern Co", sector: "Utilities" },
  { symbol: "DUK", name: "Duke Energy Corp", sector: "Utilities" },
  { symbol: "D", name: "Dominion Energy Inc", sector: "Utilities" },
  { symbol: "AEP", name: "American Electric Power", sector: "Utilities" },
  { symbol: "EXC", name: "Exelon Corp", sector: "Utilities" },
  { symbol: "SRE", name: "Sempra", sector: "Utilities" },
  { symbol: "XEL", name: "Xcel Energy Inc", sector: "Utilities" },
  { symbol: "ED", name: "Consolidated Edison Inc", sector: "Utilities" },
  { symbol: "WEC", name: "WEC Energy Group", sector: "Utilities" },
  { symbol: "ES", name: "Eversource Energy", sector: "Utilities" },
  { symbol: "AWK", name: "American Water Works", sector: "Utilities" },
  { symbol: "DTE", name: "DTE Energy Co", sector: "Utilities" },
  { symbol: "AEE", name: "Ameren Corp", sector: "Utilities" },
  { symbol: "PCG", name: "PG&E Corp", sector: "Utilities" },
  { symbol: "FE", name: "FirstEnergy Corp", sector: "Utilities" },
  { symbol: "CEG", name: "Constellation Energy Corp", sector: "Utilities" },
  { symbol: "VST", name: "Vistra Corp", sector: "Utilities" },
  { symbol: "NRG", name: "NRG Energy Inc", sector: "Utilities" },
  { symbol: "PPL", name: "PPL Corp", sector: "Utilities" },
  { symbol: "CMS", name: "CMS Energy Corp", sector: "Utilities" },
  { symbol: "CNP", name: "CenterPoint Energy", sector: "Utilities" },
  { symbol: "ATO", name: "Atmos Energy Corp", sector: "Utilities" },
  { symbol: "NI", name: "NiSource Inc", sector: "Utilities" },
  { symbol: "EVRG", name: "Evergy Inc", sector: "Utilities" },

  // ===== ADDITIONAL POPULAR / MEME / MID-CAPS =====
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc", sector: "Finance" },
  { symbol: "TCEHY", name: "Tencent Holdings Ltd", sector: "Tech" },
  { symbol: "BABA", name: "Alibaba Group Holding", sector: "Tech" },
  { symbol: "JD", name: "JD.com Inc", sector: "Retail" },
  { symbol: "PDD", name: "PDD Holdings Inc", sector: "Retail" },
  { symbol: "BIDU", name: "Baidu Inc", sector: "Tech" },
  { symbol: "SE", name: "Sea Ltd", sector: "Tech" },
  { symbol: "MELI", name: "MercadoLibre Inc", sector: "Retail" },
  { symbol: "CPNG", name: "Coupang Inc", sector: "Retail" },
  { symbol: "DKNG", name: "DraftKings Inc", sector: "Media" },
  { symbol: "PENN", name: "PENN Entertainment Inc", sector: "Media" },
  { symbol: "MGM", name: "MGM Resorts International", sector: "Media" },
  { symbol: "WYNN", name: "Wynn Resorts Ltd", sector: "Media" },
  { symbol: "LVS", name: "Las Vegas Sands Corp", sector: "Media" },
  { symbol: "NCLH", name: "Norwegian Cruise Line", sector: "Consumer" },
  { symbol: "DAL", name: "Delta Air Lines Inc", sector: "Industrial" },
  { symbol: "UAL", name: "United Airlines Holdings", sector: "Industrial" },
  { symbol: "AAL", name: "American Airlines Group", sector: "Industrial" },
  { symbol: "LUV", name: "Southwest Airlines Co", sector: "Industrial" },
  { symbol: "JBLU", name: "JetBlue Airways Corp", sector: "Industrial" },
  { symbol: "SAVE", name: "Spirit Airlines Inc", sector: "Industrial" },
  { symbol: "PLUG", name: "Plug Power Inc", sector: "Energy" },
  { symbol: "FSLR", name: "First Solar Inc", sector: "Energy" },
  { symbol: "SEDG", name: "SolarEdge Technologies", sector: "Energy" },
  { symbol: "RUN", name: "Sunrun Inc", sector: "Energy" },
  { symbol: "NOVA", name: "Sunnova Energy International", sector: "Energy" },
  { symbol: "SPWR", name: "SunPower Corp", sector: "Energy" },
  { symbol: "BE", name: "Bloom Energy Corp", sector: "Energy" },
  { symbol: "SMR", name: "NuScale Power Corp", sector: "Energy" },
  { symbol: "LEU", name: "Centrus Energy Corp", sector: "Energy" },
  { symbol: "OKLO", name: "Oklo Inc", sector: "Energy" },
  { symbol: "VALE", name: "Vale SA", sector: "Materials" },
  { symbol: "RIO", name: "Rio Tinto Group", sector: "Materials" },
  { symbol: "BHP", name: "BHP Group Ltd", sector: "Materials" },
  { symbol: "BWXT", name: "BWX Technologies Inc", sector: "Defense" },
  { symbol: "KTOS", name: "Kratos Defense & Security", sector: "Defense" },
  { symbol: "PLBY", name: "PLBY Group Inc", sector: "Media" },
  { symbol: "MNST", name: "Monster Beverage Corp", sector: "Consumer" },
  { symbol: "CELH", name: "Celsius Holdings Inc", sector: "Consumer" },
  { symbol: "SAM", name: "Boston Beer Co", sector: "Consumer" },
  { symbol: "TAP", name: "Molson Coors Beverage", sector: "Consumer" },
  { symbol: "BUD", name: "Anheuser-Busch InBev SA", sector: "Consumer" },
  { symbol: "DEO", name: "Diageo PLC", sector: "Consumer" },
  { symbol: "SYY", name: "Sysco Corp", sector: "Consumer" },
  { symbol: "USFD", name: "US Foods Holding Corp", sector: "Consumer" },
  { symbol: "DRI", name: "Darden Restaurants Inc", sector: "Consumer" },
  { symbol: "BROS", name: "Dutch Bros Inc", sector: "Consumer" },
  { symbol: "CARG", name: "CarGurus Inc", sector: "Auto" },
  { symbol: "CVNA", name: "Carvana Co", sector: "Auto" },
  { symbol: "KMX", name: "CarMax Inc", sector: "Retail" },
  { symbol: "XPEL", name: "XPEL Inc", sector: "Auto" },
  { symbol: "LAZR", name: "Luminar Technologies", sector: "Auto" },
  { symbol: "CPRT", name: "Copart Inc", sector: "Industrial" },
  { symbol: "ODFL", name: "Old Dominion Freight Line", sector: "Industrial" },
  { symbol: "SAIA", name: "Saia Inc", sector: "Industrial" },
  { symbol: "XPO", name: "XPO Inc", sector: "Industrial" },
  { symbol: "LSTR", name: "Landstar System Inc", sector: "Industrial" },
  { symbol: "EXPD", name: "Expeditors International", sector: "Industrial" },
  { symbol: "PAYC", name: "Paycom Software Inc", sector: "Tech" },
  { symbol: "PAYX", name: "Paychex Inc", sector: "Tech" },
  { symbol: "ADP", name: "Automatic Data Processing", sector: "Tech" },
  { symbol: "BR", name: "Broadridge Financial", sector: "Finance" },
  { symbol: "MSCI", name: "MSCI Inc", sector: "Finance" },
  { symbol: "NDAQ", name: "Nasdaq Inc", sector: "Finance" },
  { symbol: "CBOE", name: "Cboe Global Markets", sector: "Finance" },
  { symbol: "MCO", name: "Moody's Corp", sector: "Finance" },
  { symbol: "FLT", name: "Fleetcor Technologies", sector: "Finance" },
  { symbol: "WTW", name: "Willis Towers Watson", sector: "Finance" },
  { symbol: "CINF", name: "Cincinnati Financial", sector: "Finance" },
  { symbol: "RJF", name: "Raymond James Financial", sector: "Finance" },
  { symbol: "LPLA", name: "LPL Financial Holdings", sector: "Finance" },
  { symbol: "ALLY", name: "Ally Financial Inc", sector: "Finance" },
  { symbol: "SYF", name: "Synchrony Financial", sector: "Finance" },
  { symbol: "WRB", name: "W.R. Berkley Corp", sector: "Finance" },
  { symbol: "L", name: "Loews Corp", sector: "Finance" },
  { symbol: "ACGL", name: "Arch Capital Group Ltd", sector: "Finance" },
  { symbol: "RE", name: "Everest Group Ltd", sector: "Finance" },
  { symbol: "RNR", name: "RenaissanceRe Holdings", sector: "Finance" },
];

async function main() {
  console.log("Seeding watchlist...");

  let count = 0;
  for (const stock of STOCKS) {
    await prisma.watchlistStock.upsert({
      where: { symbol: stock.symbol },
      update: { name: stock.name, sector: stock.sector },
      create: stock,
    });
    count++;
    if (count % 50 === 0) console.log(`  ${count}/${STOCKS.length} stocks seeded...`);
  }

  console.log(`\nSeeded ${STOCKS.length} stocks to watchlist.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
